version: '3.0'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - go_academy:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
volumes:
  go_academy:
