version: '3'

services:
  web:
    build:
      context: .
    tty: true
    ports:
      - 8080:8080
    volumes:
      - .:/go/src
    environment:
      GOPATH: /go
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db:3306
      DB__DATABASE: test_db
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - go_academy:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
volumes:
  go_academy:
