version: '3'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - item-throw-ways:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: item_throw_ways
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - external
volumes:
  item-throw-ways:
networks:
  external:
    driver: bridge
    internal: false
    name: item-throw-ways
