version: '3'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - go_academy:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
        - external
volumes:
  go_academy:
networks:
  external:
    driver: bridge
    internal: false
    name: go-academy
