version: '3'

services:
  web:
    build:
      context: .
    tty: true
    volumes:
      - .:/go/src
    ports:
      - 8080:8080
    environment:
      GOPATH: /go
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - item-throw-ways:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
volumes:
  item-throw-ways:
