AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  item-throw-ways

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Environment:
      Variables:
        DB_USER: !Ref DbUser
        DB_PASSWORD: !Ref DbPassword
        DB_NAME: !Ref DbName
        DB_HOST: !Ref DbHost
        HIRAGANA_TRANSLATE_APP_ID: !Ref HiraganaTranslationAppId
Resources:
  ApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cmd/api/
      Handler: main
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: GET
UpdateItemsFunction:
  Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  Properties:
    CodeUri: cmd/batch/update_items
    Handler: update_items
    Runtime: go1.x
    Events:
      ScheduleEvent:
        Type: Schedule
        Properties:
          Schedule: rate(1 day)
    Timeout: 300
    Environment:
      Variables:
        HIRAGANA_TRANSLATION_APP_ID: HIRAGANA_TRANSLATION_APP_ID
UpdateAreaCollectWeekdaysFunction:
  Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  Properties:
    CodeUri: cmd/batch/update_area_collect_weekdays
    Handler: update_area_collect_weekdays
    Runtime: go1.x
    Events:
      ScheduleEvent:
        Type: Schedule
        Properties:
          Schedule: rate(1 day)
    Timeout: 300
Parameters:
  DbUser:
    Type: String
  DbPassword:
    Type: String
  DbName:
    Type: String
  DbHost:
    Type: String
  HiraganaTranslationAppId:
    Type: String

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  HelloWorldFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
